/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO rule-adoption Phase 4 W4.11 end-to-end.
 *
 * Run locally with:
 *   yarn cypress:run-without-security --spec \
 *     .cypress/integration/slo_test/adoption.spec.js
 *
 * Requires the observability-stack dev cluster (Cortex-backed `prometheus`
 * container + a DirectQuery datasource named by `sloDatasourceId`) and the
 * feature flags `observability.slo.ruleDedup.enabled` /
 * `observability.slo.ruleAdoption.enabled` set to true. When either flag is
 * off the server returns 412 on `/_orphans`; the spec detects that in a
 * `before` hook and skips every `it()` so CI stays green regardless of the
 * runtime config.
 *
 * Scenarios (per W4.11):
 *
 *   1. Lost-SO recovery — create an SLO, backdoor-delete the saved object
 *      so the rule group is "owner-less", open the Recover tab, click
 *      Recover, and assert the SLO reappears on the listing.
 *   2. Tamper — backdoor-delete the SO and then tamper with the recording
 *      group via the ruler admin API. The row renders with a drift badge
 *      and the Recover button is disabled.
 *   3. Cross-datasource clone — clone an orphan from datasource A into
 *      datasource B (single-OSD variant; the plan's dual-OSD phrasing is a
 *      stretch the service-side integration test in W4.10 already covers).
 *   4. No-external-vendor DOM assertion — explicit check that the external
 *      dashboards vendor is not named on either tab of the adoption page.
 *
 * Backdoor-delete path: the plugin does not expose a test-only hook that
 * removes the SLO saved object without also tearing down the ruler-side
 * rule group, which is exactly the precondition the adoption surface needs.
 * We therefore delete the saved object directly through the core
 * `/api/saved_objects/<type>/<id>` endpoint with the `osd-xsrf` header;
 * this leaves the ruler rule group behind, re-creating the orphan state
 * the reconciler surfaces via `_orphans`.
 */

const SLO_BASE = '/api/observability/v1/slos';
const SAVED_OBJECTS_BASE = '/api/saved_objects';
// Saved-object type used by the SLO plugin. Kept in sync with
// server/saved_objects/slo_definition.ts; if the SO type rename lands the
// adoption spec needs an update too. Tracked in the plan.
const SLO_SO_TYPE = 'slo-definition';
const APP_ID = 'observability-apm-slo';
// Cortex / Prometheus-compatible ruler admin root (see the plugin CLAUDE.md —
// "SLO ruler dual-write against Cortex" section). Ruler admin is unprefixed.
const RULER_ROOT = Cypress.env('rulerRoot') || 'http://localhost:9090';

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

// ---------------------------------------------------------------------------
// Fixture builders — inlined per workstream rules (no shared helpers touched)
// ---------------------------------------------------------------------------

function buildMinimalSloSpec(datasourceId, name) {
  return {
    datasourceId,
    name,
    description: 'Cypress adoption spec — autogenerated',
    enabled: true,
    mode: 'active',
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        metric: 'http_requests_total',
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: 'cypress-svc' }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

/** Create an SLO via the plugin API. Yields the resolved id (or null on failure). */
function createSlo(datasourceId, name) {
  return cy
    .request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildMinimalSloSpec(datasourceId, name) },
      failOnStatusCode: false,
    })
    .then((resp) => {
      if (resp.status === 200 || resp.status === 201) {
        return {
          id: resp.body.id,
          provisioning: (resp.body.status && resp.body.status.provisioning) || null,
        };
      }
      return { id: null, provisioning: null };
    });
}

/** Delete an SLO via the plugin API (tears down the rule group too). */
function deleteSlo(sloId) {
  if (!sloId) return;
  cy.request({
    method: 'DELETE',
    url: `${SLO_BASE}/${encodeURIComponent(sloId)}`,
    headers: { 'osd-xsrf': 'true' },
    failOnStatusCode: false,
  });
}

/**
 * Backdoor-delete the SLO saved object directly through the core SO REST
 * surface. Leaves the ruler rule group in place so the reconciler surfaces
 * it as an adoptable orphan.
 */
function backdoorDeleteSo(sloId) {
  cy.request({
    method: 'DELETE',
    url: `${SAVED_OBJECTS_BASE}/${SLO_SO_TYPE}/${encodeURIComponent(sloId)}`,
    headers: { 'osd-xsrf': 'true' },
    qs: { force: true },
    failOnStatusCode: false,
  });
}

/**
 * Tamper with the recording group via the Cortex / Prometheus-compatible
 * ruler admin API. The endpoint lives at the unprefixed root per the plugin
 * CLAUDE.md. `provisioning` comes from the SLO create response.
 */
function tamperRulerGroup(provisioning) {
  if (!provisioning || !provisioning.rulerNamespace || !provisioning.ruleGroupName) return;
  cy.request({
    method: 'DELETE',
    url: `${RULER_ROOT}/api/v1/rules/${encodeURIComponent(
      provisioning.rulerNamespace
    )}/${encodeURIComponent(provisioning.ruleGroupName)}`,
    failOnStatusCode: false,
  });
}

// ---------------------------------------------------------------------------
// Spec
// ---------------------------------------------------------------------------

describe('SLO rule adoption — Phase 4 W4.11', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  // Second datasource for the cross-datasource clone scenario. Defaults to a
  // second prom backend the observability-stack init script seeds; override
  // via `cypress.config.js` env if the local fixture uses a different name.
  const datasourceIdB =
    Cypress.env('sloDatasourceIdB') || Cypress.env('sloSecondDatasourceId') || 'prom_integ_test_b';

  // Per-it trackers so the after hook can mop up whatever each scenario
  // landed, regardless of where it bailed.
  let lostSloId = null;
  let tamperSloId = null;
  let cloneSourceSloId = null;
  let cloneTargetSloId = null;
  // Whether the server has the adoption feature flags on. Set in the before
  // hook; used by every it() to decide whether to skip.
  let adoptionEnabled = false;

  before(function () {
    // Feature-flag gate. If the server returns 412 the flags are off in this
    // environment; skip the whole describe rather than fail CI.
    cy.request({
      method: 'GET',
      url: `${SLO_BASE}/_orphans`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    }).then((res) => {
      if (res.status === 412) {
        cy.log('Adoption feature flags disabled — skipping adoption.spec.js');
        adoptionEnabled = false;
      } else {
        adoptionEnabled = true;
      }
    });
  });

  after(() => {
    // Cleanup — best-effort. Each delete is idempotent and never fails the run.
    [lostSloId, tamperSloId, cloneSourceSloId, cloneTargetSloId]
      .filter(Boolean)
      .forEach((id) => deleteSlo(id));
  });

  it('recovers a lost SLO via the adoption admin page', function () {
    if (!adoptionEnabled) {
      this.skip();
      return;
    }

    const name = randomId('adoption-lost-1');
    createSlo(datasourceId, name).then(({ id, provisioning }) => {
      expect(id, 'SLO create returned an id').to.be.a('string');
      lostSloId = id;

      // Sanity: the ruler side created the alert + recording groups. Only assert
      // when the provisioning block is Prometheus-backed; other backends
      // would simply skip the ruler step.
      if (provisioning && provisioning.backend === 'prometheus') {
        expect(provisioning.ruleGroupName, 'ruleGroupName').to.be.a('string');
        expect(provisioning.rulerNamespace, 'rulerNamespace').to.be.a('string');
      }

      // Backdoor-delete the SO so the rule group is orphaned.
      backdoorDeleteSo(id);

      // Navigate to the adoption page. The Recover tab is the default
      // landing tab per Batch 3's router; `#?tab=recover` is accepted too.
      cy.visit(`/app/${APP_ID}#/slos/adoption`);

      // Adoption page shell — data-test-subj assumed — verify against Batch 3 UI once landed.
      cy.get('[data-test-subj="sloAdoptionPage"]', { timeout: 30000 }).should('be.visible');

      // The orphan row is keyed on the SLO id. The `_orphans` endpoint is
      // reconciler-backed, so the first GET will sweep live and surface the
      // orphan synchronously.
      cy.get(`[data-test-subj="sloAdoption-orphanRow-${id}"]`, { timeout: 30000 })
        .should('be.visible')
        // data-test-subj assumed — verify against Batch 3 UI once landed.
        .within(() => {
          cy.get('[data-test-subj="sloAdoption-orphanIntegrityBadge-ok"]').should('be.visible');
          cy.get('[data-test-subj="sloAdoption-recoverButton"]')
            .should('not.be.disabled')
            .click();
        });

      // EUI success toast — Batch 3's copy is "SLO recovered" per the plan.
      cy.get('.euiToast--success', { timeout: 20000 })
        .should('be.visible')
        .and('contain.text', 'SLO recovered');

      // Back to listing — the recovered SLO should render with a non-missing
      // rule-health badge.
      cy.visit(`/app/${APP_ID}#/slos`);
      cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
      cy.get(`[data-test-subj="slosRulesBadge-${id}"]`, { timeout: 30000 })
        .should('have.attr', 'data-test-rule-state')
        .and('not.equal', 'missing');
    });
  });

  it('disables Recover and surfaces the drift callout when the recording rule is tampered', function () {
    if (!adoptionEnabled) {
      this.skip();
      return;
    }

    const name = randomId('adoption-tamper-1');
    createSlo(datasourceId, name).then(({ id, provisioning }) => {
      expect(id, 'SLO create returned an id').to.be.a('string');
      tamperSloId = id;

      // Step 1 — orphan the saved object.
      backdoorDeleteSo(id);
      // Step 2 — tamper with the ruler group so `specIntegrity !== 'ok'`.
      // The reconciler treats an out-of-band edit/delete of the recording
      // group as drift and the row surfaces "Spec drift detected".
      tamperRulerGroup(provisioning);

      cy.visit(`/app/${APP_ID}#/slos/adoption`);
      cy.get('[data-test-subj="sloAdoptionPage"]', { timeout: 30000 }).should('be.visible');

      // Row exists, but integrity flips to drift and recover is disabled.
      // data-test-subj assumed — verify against Batch 3 UI once landed.
      cy.get(`[data-test-subj="sloAdoption-orphanRow-${id}"]`, { timeout: 30000 })
        .should('be.visible')
        .within(() => {
          cy.get('[data-test-subj="sloAdoption-orphanIntegrityBadge-drift"]')
            .should('be.visible')
            .and('contain.text', 'drift');
          cy.get('[data-test-subj="sloAdoption-recoverButton"]').should(
            'satisfy',
            ($btn) =>
              $btn.is(':disabled') ||
              $btn.attr('aria-disabled') === 'true' ||
              $btn.attr('disabled') !== undefined
          );
          // Expand the row for the drift-explainer callout.
          cy.get('[data-test-subj="sloAdoption-orphanRowExpand"]').click();
        });

      // The callout copy mentions out-of-band / drift. Case-insensitive so
      // whatever Batch 3 settled on is accepted.
      cy.get('[data-test-subj="sloAdoption-driftCallout"]', { timeout: 10000 })
        .should('be.visible')
        .invoke('text')
        .then((text) => {
          expect(text.toLowerCase()).to.match(/out[- ]of[- ]band|drift/);
        });
    });
  });

  it('clones an SLO into another datasource', function () {
    if (!adoptionEnabled) {
      this.skip();
      return;
    }
    if (datasourceId === datasourceIdB) {
      cy.log('No second datasource configured (sloSecondDatasourceId); skipping clone scenario');
      this.skip();
      return;
    }

    const sourceName = randomId('adoption-clone-source');
    const targetName = randomId('adoption-clone-target');
    createSlo(datasourceId, sourceName).then(({ id: sourceId }) => {
      expect(sourceId, 'source SLO create returned an id').to.be.a('string');
      cloneSourceSloId = sourceId;

      cy.visit(`/app/${APP_ID}#/slos/adoption?tab=clone`);
      cy.get('[data-test-subj="sloAdoptionPage"]', { timeout: 30000 }).should('be.visible');

      // Clone tab — the tab button is stable across reloads, but the query
      // param already selects it; click as a belt-and-braces guard.
      // data-test-subj assumed — verify against Batch 3 UI once landed.
      cy.get('[data-test-subj="sloAdoption-tab-clone"]').click();

      // Source datasource picker — select datasource A.
      cy.get('[data-test-subj="sloAdoption-cloneSourceDatasource"]')
        .click()
        .get(`[data-test-subj="sloAdoption-cloneSourceDatasource-option-${datasourceId}"]`)
        .click();

      // Adoptable rows for datasource A should include the one we just seeded.
      // data-test-subj assumed — verify against Batch 3 UI once landed.
      cy.get(`[data-test-subj="sloAdoption-cloneRow-${sourceId}"]`, { timeout: 30000 })
        .should('be.visible')
        .find('[data-test-subj="sloAdoption-cloneRowCheckbox"]')
        .click();

      // Target datasource picker — select datasource B.
      cy.get('[data-test-subj="sloAdoption-cloneTargetDatasource"]')
        .click()
        .get(`[data-test-subj="sloAdoption-cloneTargetDatasource-option-${datasourceIdB}"]`)
        .click();

      // Optional override name so the cloned SLO is easy to identify + clean up.
      cy.get('[data-test-subj="sloAdoption-cloneOverrideName"]').clear().type(targetName);

      cy.get('[data-test-subj="sloAdoption-cloneSubmit"]').click();

      // Success toast + id for cleanup. The clone response body carries the
      // new SLO id in a `data-test-clone-id` attribute per Batch 3.
      cy.get('.euiToast--success', { timeout: 30000 })
        .should('be.visible')
        .and('contain.text', 'cloned');

      // Verify via the plugin API that the target SLO landed on datasource B.
      cy.request({
        method: 'GET',
        url: SLO_BASE,
        headers: { 'osd-xsrf': 'true' },
        qs: { datasourceId: datasourceIdB },
        failOnStatusCode: false,
      }).then((resp) => {
        expect(resp.status).to.eq(200);
        const items = (resp.body && resp.body.items) || [];
        const cloned = items.find((s) => s.name === targetName);
        expect(cloned, `clone ${targetName} present on ${datasourceIdB}`).to.not.be.undefined;
        cloneTargetSloId = cloned.id;
      });

      // The source SLO is still listed on datasource A (clone does not move).
      cy.request({
        method: 'GET',
        url: SLO_BASE,
        headers: { 'osd-xsrf': 'true' },
        qs: { datasourceId },
        failOnStatusCode: false,
      }).then((resp) => {
        expect(resp.status).to.eq(200);
        const items = (resp.body && resp.body.items) || [];
        const source = items.find((s) => s.id === sourceId);
        expect(source, 'source SLO still present on datasource A').to.not.be.undefined;
      });
    });
  });

  it('does not mention the external dashboards vendor by name anywhere on the adoption page', function () {
    if (!adoptionEnabled) {
      this.skip();
      return;
    }

    // Recover tab first.
    cy.visit(`/app/${APP_ID}#/slos/adoption`);
    cy.get('[data-test-subj="sloAdoptionPage"]', { timeout: 30000 }).should('be.visible');
    // Any of: Recover-tab list, empty-prompt, or server-error callout — we
    // only require that the page chrome rendered before we assert absence.
    // Plan constraint: no external dashboards vendor named in the DOM.
    cy.contains(/grafana/i).should('not.exist');

    // Clone tab.
    // data-test-subj assumed — verify against Batch 3 UI once landed.
    cy.get('[data-test-subj="sloAdoption-tab-clone"]').click();
    cy.contains(/grafana/i).should('not.exist');
  });
});
